package game.modelos;

public enum TipoElemento {
    NORMAL, LUTADOR, VOADOR,
    VENENOSO, TERRESTRE, PEDRA,
    INSETO, FANTASMA, ACO,
    FOGO, AGUA, GRAMA,
    ELETRICO, PSIQUICO, GELO,
    DRAGAO, NOTURNO, FADA, NENHUM
}